language: python
python:
 - "3.8"
env:
 - LC_ALL=en_US.utf-8
install:
 - pip install -r requirements-dev.txt #fix versions
 - pip install -e .
script:
 - flake8
 - py.test --cov urihandler --cov-report term-missing tests
after_success:
 - coveralls
