name: urihandler backend tests

on:
  workflow_dispatch:

  pull_request:
    paths:
      - urihandler/**
      - .github/workflows/urihandler.yaml
      - scripts/**
      - pyproject.toml
      - requirements*.txt
      - tests/**

  push:
    branches:
      - main
env:
  PYTHON_VERSION: '3.11'

jobs:
  test:
    name: Bacend tests

    services:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install python requirements
        env:
          HATCH_BUILD_NO_HOOKS: true
        run: |
          pip install pip-tools
          pip-sync requirements-ci.txt
          pip install -e .

      - name: Python tests
        env:
          REDIS_HOST: redis
          REDIS_PORT: 6379
        run: |
          flake8
          py.test --cov urihandler --cov-report term-missing tests